// ── Works Data ── single source of truth for all portfolio projects
var WORKS_DATA = [

  // ── Websites ──────────────────────────────────────────────────────────
  {
    id: 'ecommerce-store',
    category: 'websites',
    categoryLabel: 'مواقع الكترونية',
    icon: 'ri-global-line',
    gradient: 'linear-gradient(135deg, #1a1a2e 0%, #16213e 100%)',
    colors: ['#1a1a2e', '#16213e', '#0f3460'],
    title: 'موقع متجر إلكتروني',
    shortDesc: 'تصميم وتطوير متجر إلكتروني متكامل بتجربة مستخدم سلسة',
    fullDesc: 'صمّمنا وطوّرنا متجراً إلكترونياً متكاملاً يجمع بين الجمال البصري والأداء التقني العالي. المشروع يضم واجهة مستخدم سلسة وعصرية مع دعم كامل لعمليات الدفع الإلكتروني والشحن والتتبع.\n\nبنينا المنصة على أحدث التقنيات لضمان سرعة التحميل وأمان المعاملات، وضمّنّا نظام إدارة مخزون متكامل مع تقارير مبيعات تفصيلية وأدوات تسويق داخلية.\n\nالنتيجة كانت منصة تجارية قوية حققت للعميل زيادة بنسبة 150% في المبيعات خلال ثلاثة أشهر من الإطلاق.',
    client: 'شركة التجارة الذكية',
    year: '2025',
    services: ['تصميم UI/UX', 'تطوير الواجهة الأمامية', 'تطوير الخلفية', 'تكامل نظام الدفع'],
    tags: ['React', 'Node.js', 'MongoDB', 'Stripe'],
    results: ['زيادة المبيعات 150%', 'تحسين التحويل 80%', 'تقليل وقت التحميل 60%'],
    galleryIcons: ['ri-layout-3-line','ri-shopping-cart-2-line','ri-smartphone-line','ri-secure-payment-line','ri-bar-chart-2-line','ri-settings-3-line']
  },
  {
    id: 'services-website',
    category: 'websites',
    categoryLabel: 'مواقع الكترونية',
    icon: 'ri-code-s-slash-line',
    gradient: 'linear-gradient(135deg, #0f3460 0%, #533483 100%)',
    colors: ['#0f3460', '#533483', '#1a1a2e'],
    title: 'موقع شركة خدمات',
    shortDesc: 'موقع تعريفي احترافي لشركة رائدة في مجال الخدمات',
    fullDesc: 'أنجزنا موقعاً تعريفياً احترافياً يعكس هوية الشركة ويُبرز خدماتها بأسلوب بصري مقنع. صُمّم الموقع لتحقيق أعلى معدلات تحويل الزوار إلى عملاء محتملين.\n\nالموقع مبني بمعايير SEO الحديثة لضمان الظهور في نتائج البحث، ومتوافق مع جميع الأجهزة من هاتف ومتجر وحاسوب.\n\nحقق الموقع ارتفاعاً فورياً في حركة الزيارات العضوية بنسبة 200% خلال الشهرين الأولين من الإطلاق.',
    client: 'مجموعة الخدمات المتكاملة',
    year: '2025',
    services: ['تصميم UI/UX', 'تطوير Full-Stack', 'تحسين SEO', 'صيانة ودعم فني'],
    tags: ['Next.js', 'TailwindCSS', 'Framer Motion', 'Vercel'],
    results: ['ارتفاع الزيارات 200%', 'تحسين SEO 90%', 'تحويل الزوار 65%'],
    galleryIcons: ['ri-layout-grid-line','ri-service-line','ri-team-line','ri-search-eye-line','ri-speed-line','ri-customer-service-2-line']
  },
  {
    id: 'news-portal',
    category: 'websites',
    categoryLabel: 'مواقع الكترونية',
    icon: 'ri-layout-masonry-line',
    gradient: 'linear-gradient(135deg, #2c3e50 0%, #3498db 100%)',
    colors: ['#2c3e50', '#3498db', '#1a6ea8'],
    title: 'بوابة إخبارية',
    shortDesc: 'موقع إخباري بتصميم عصري وسرعة تحميل فائقة',
    fullDesc: 'طوّرنا بوابة إخبارية متكاملة تدير آلاف المقالات يومياً بكفاءة عالية. يتميز الموقع بواجهة تحريرية سهلة وسرعة تحميل تحت ثانيتين حتى في أوقات الذروة.\n\nيشمل المشروع نظام تصنيف وبحث متقدم وخاصية الدفع المقيّد للمحتوى المميز وإشعارات فورية للمشتركين.\n\nأصبح الموقع من أسرع البوابات الإخبارية في المنطقة وحقق مليون زيارة شهرية في أول ستة أشهر.',
    client: 'مؤسسة الإعلام الرقمي',
    year: '2024',
    services: ['تصميم UI/UX', 'تطوير CMS مخصص', 'تحسين الأداء', 'نظام الاشتراكات'],
    tags: ['WordPress', 'React', 'MySQL', 'CloudFlare'],
    results: ['مليون زيارة شهرية', 'وقت تحميل 1.8 ثانية', 'تقليل معدل الارتداد 45%'],
    galleryIcons: ['ri-newspaper-line','ri-article-line','ri-book-open-line','ri-notification-4-line','ri-search-line','ri-home-3-line']
  },
  {
    id: 'fashion-store',
    category: 'websites',
    categoryLabel: 'مواقع الكترونية',
    icon: 'ri-store-2-line',
    gradient: 'linear-gradient(135deg, #0d0d0d 0%, #434343 100%)',
    colors: ['#0d0d0d', '#434343', '#d42b1e'],
    title: 'متجر أزياء',
    shortDesc: 'متجر إلكتروني فاخر لعلامة أزياء سعودية',
    fullDesc: 'صممنا تجربة تسوق أزياء فاخرة تعكس رقي العلامة التجارية. الموقع يُقدّم المنتجات بطريقة بصرية ساحرة مع إمكانية تجربة المنتجات افتراضياً.\n\nيضم المتجر خاصية الفلترة الذكية والتوصيات المخصصة بالذكاء الاصطناعي وتتبع الطلبات بالزمن الفعلي.\n\nحقق المتجر مبيعات تجاوزت مليون ريال في الشهر الأول من إطلاقه.',
    client: 'دار أزياء النخبة',
    year: '2025',
    services: ['تصميم UI/UX فاخر', 'تطوير التجارة الإلكترونية', 'تكامل التجربة الافتراضية', 'تحسين تجربة الدفع'],
    tags: ['Shopify Plus', 'React', 'Three.js', 'Stripe'],
    results: ['مليون ريال مبيعات', 'متوسط قيمة الطلب +40%', 'نسبة العودة 70%'],
    galleryIcons: ['ri-t-shirt-2-line','ri-shopping-bag-3-line','ri-user-heart-line','ri-star-line','ri-gift-line','ri-price-tag-3-line']
  },

  // ── Social Media ──────────────────────────────────────────────────────
  {
    id: 'ad-campaign',
    category: 'social',
    categoryLabel: 'سوشيال ميديا',
    icon: 'ri-instagram-line',
    gradient: 'linear-gradient(135deg, #e07428 0%, #d42b1e 100%)',
    colors: ['#e07428', '#d42b1e', '#bc0000'],
    title: 'حملة إعلانية متكاملة',
    shortDesc: 'إدارة وتصميم محتوى سوشيال ميديا لحملة تسويقية شاملة',
    fullDesc: 'أدرنا حملة تسويقية متكاملة عبر جميع منصات التواصل الاجتماعي الرئيسية مع إنتاج محتوى بصري احترافي يتناسب مع كل منصة وجمهورها المستهدف.\n\nشملت الحملة تصميم أكثر من 200 قطعة إبداعية من بوستات وستوريز وريلز وبنرات إعلانية مع كتابة النصوص التسويقية المحفّزة.\n\nحققت الحملة وصولاً يتجاوز مليوني مستخدم وتفاعلاً بنسبة 12% وهو أعلى بخمسة أضعاف من معدل الصناعة.',
    client: 'مجموعة الفهد التجارية',
    year: '2025',
    services: ['استراتيجية المحتوى', 'تصميم جهوي', 'كتابة النصوص', 'إدارة الإعلان'],
    tags: ['Instagram', 'Facebook', 'TikTok', 'Canva Pro', 'Adobe Suite'],
    results: ['وصول 2 مليون مستخدم', 'معدل تفاعل 12%', 'زيادة المبيعات 95%'],
    galleryIcons: ['ri-instagram-line','ri-facebook-circle-line','ri-tiktok-line','ri-bar-chart-grouped-line','ri-vidicon-line','ri-image-2-line']
  },
  {
    id: 'social-management',
    category: 'social',
    categoryLabel: 'سوشيال ميديا',
    icon: 'ri-twitter-x-line',
    gradient: 'linear-gradient(135deg, #c2185b 0%, #e91e63 100%)',
    colors: ['#c2185b', '#e91e63', '#ad1457'],
    title: 'إدارة حسابات تواصل',
    shortDesc: 'محتوى إبداعي لمنصات التواصل الاجتماعي',
    fullDesc: 'تولّينا إدارة كاملة لحسابات العميل عبر أربع منصات رئيسية بمحتوى مُخطّط بعناية يعكس هوية العلامة التجارية ويبني علاقة متينة مع الجمهور.\n\nاعتمدنا استراتيجية محتوى تجمع بين التعليم والترفيه والبيع بأسلوب غير مباشر يحقق نمواً عضوياً مستداماً.\n\nنجحنا في مضاعفة عدد المتابعين خلال ستة أشهر مع رفع معدل التفاعل من 1.2% إلى 8.9%.',
    client: 'مطاعم الشيف الذهبي',
    year: '2024',
    services: ['تخطيط المحتوى', 'التصميم الجرافيكي', 'إنتاج الفيديو', 'الرد على التعليقات'],
    tags: ['Instagram', 'Twitter/X', 'Snapchat', 'TikTok'],
    results: ['مضاعفة المتابعين x2', 'تفاعل 8.9%', 'نمو المبيعات 70%'],
    galleryIcons: ['ri-calendar-schedule-line','ri-quill-pen-line','ri-image-edit-line','ri-heart-pulse-line','ri-message-3-line','ri-line-chart-line']
  },
  {
    id: 'tiktok-content',
    category: 'social',
    categoryLabel: 'سوشيال ميديا',
    icon: 'ri-tiktok-line',
    gradient: 'linear-gradient(135deg, #ff6b35 0%, #f7931e 100%)',
    colors: ['#ff6b35', '#f7931e', '#d42b1e'],
    title: 'محتوى تيك توك',
    shortDesc: 'إنتاج محتوى إبداعي لمنصة تيك توك',
    fullDesc: 'أنتجنا سلسلة من الفيديوهات القصيرة المُصمّمة خصيصاً لخوارزمية تيك توك مع الحرص على تقديم قيمة حقيقية للمشاهد والمحافظة على أسلوب العلامة التجارية.\n\nكل فيديو مصنوع بجودة إنتاجية عالية ومُحسّن للمشاهدة الكاملة والمشاركة الفورية من اللحظة الأولى.\n\nحقق حساب العميل 500 ألف متابع في أربعة أشهر وفيديو واحد تجاوز 5 ملايين مشاهدة.',
    client: 'علامة التسلية والترفيه',
    year: '2025',
    services: ['استراتيجية TikTok', 'إنتاج الفيديو', 'موشن جرافيك', 'تحليل الأداء'],
    tags: ['TikTok', 'CapCut/PR', 'After Effects', 'Analytics'],
    results: ['500K متابع', '5M مشاهدة للفيديو الأبرز', 'معدل اكتمال 85%'],
    galleryIcons: ['ri-tiktok-line','ri-vidicon-2-line','ri-film-line','ri-play-circle-line','ri-music-2-line','ri-star-smile-line']
  },
  {
    id: 'paid-ads',
    category: 'social',
    categoryLabel: 'سوشيال ميديا',
    icon: 'ri-advertisement-line',
    gradient: 'linear-gradient(135deg, #405de6 0%, #833ab4 50%, #fd1d1d 100%)',
    colors: ['#405de6', '#833ab4', '#fd1d1d'],
    title: 'حملة إعلانات ممولة',
    shortDesc: 'إدارة حملات إعلانية ممولة على منصات التواصل',
    fullDesc: 'أدرنا حملات إعلانية ممولة بميزانيات كبيرة عبر Meta وGoogle وTikTok مع ضمان أعلى عائد ممكن على الاستثمار من خلال الاستهداف الدقيق والتحسين المستمر.\n\nاعتمدنا منهجية A/B Testing صارمة لاختبار التصاميم والنصوص والجماهير المستهدفة للوصول لأفضل مزيج تسويقي.\n\nحققنا عائداً على الإنفاق الإعلاني (ROAS) بلغ 8.5x مقارنة بـ 2.1x كان العميل يحققه قبل تعاملنا معه.',
    client: 'شبكة مراكز الياقة البدنية',
    year: '2025',
    services: ['إدارة Meta Ads', 'إدارة Google Ads', 'إدارة TikTok Ads', 'تحليل البيانات'],
    tags: ['Meta Business', 'Google Ads', 'TikTok Ads', 'Google Analytics'],
    results: ['ROAS 8.5x', 'تخفيض تكلفة الاقتناء 60%', 'زيادة التسجيلات 320%'],
    galleryIcons: ['ri-advertisement-line','ri-funds-line','ri-pie-chart-2-line','ri-target-line','ri-money-dollar-circle-line','ri-award-line']
  },

  // ── Graphic Design ────────────────────────────────────────────────────
  {
    id: 'brand-identity',
    category: 'graphic',
    categoryLabel: 'الجرافيك',
    icon: 'ri-palette-line',
    gradient: 'linear-gradient(135deg, #a00020 0%, #d42b1e 100%)',
    colors: ['#a00020', '#d42b1e', '#e07428'],
    title: 'هوية بصرية متكاملة',
    shortDesc: 'تصميم هوية بصرية احترافية لعلامة تجارية رائدة',
    fullDesc: 'صمّمنا هوية بصرية متكاملة تعبّر بعمق عن قيم الشركة وتطلعاتها، تبدأ من دراسة المنافسين والسوق وصولاً إلى الشعار وجميع مطبوعاته.\n\nتضمّنت الهوية الشعار الأساسي والبديل وأكواد الألوان الرسمية ومنظومة الخطوط وتطبيقات الهوية على جميع المواد التسويقية.\n\nسلّمنا للعميل دليل هوية بصرية شامل يغطي 40+ تطبيقاً من بطاقة العمل إلى واجهة السيارات إلى الموقع.',
    client: 'مجموعة الريادة للاستثمار',
    year: '2024',
    services: ['دراسة هوية العلامة', 'تصميم الشعار', 'نظام الألوان والخطوط', 'دليل الهوية'],
    tags: ['Illustrator', 'Photoshop', 'InDesign', 'Brand Strategy'],
    results: ['40+ تطبيق للهوية', 'تحسين التعرف بالعلامة 85%', 'رضا العميل 100%'],
    galleryIcons: ['ri-palette-line','ri-pen-nib-line','ri-font-size-2','ri-brush-line','ri-award-fill','ri-bookmark-fill']
  },
  {
    id: 'social-designs',
    category: 'graphic',
    categoryLabel: 'الجرافيك',
    icon: 'ri-brush-line',
    gradient: 'linear-gradient(135deg, #ff6f61 0%, #de4313 100%)',
    colors: ['#ff6f61', '#de4313', '#b03a2e'],
    title: 'تصاميم سوشيال ميديا',
    shortDesc: 'تصاميم إبداعية جذابة لمنصات التواصل',
    fullDesc: 'أنتجنا مكتبة تصاميم بصرية شاملة لجميع منصات التواصل الاجتماعي تتضمن قوالب قابلة للتخصيص وتصاميم حصرية موسمية ومناسباتية للعميل.\n\nحرصنا على الانسجام البصري الكامل بين جميع التصاميم مع مرونة كافية لتغطية المحتوى المتنوع دون فقدان هوية العلامة.\n\nالمكتبة تضم 300+ تصميم جاهز يُمكّن فريق العميل من النشر يومياً بجودة احترافية ثابتة.',
    client: 'سلسلة مراكز التجميل Glow',
    year: '2025',
    services: ['تصميم Templates', 'تصاميم موسمية', 'تصاميم منتجات', 'ستوريز وريلز'],
    tags: ['Adobe Photoshop', 'Illustrator', 'Figma', 'After Effects'],
    results: ['300+ تصميم جاهز', 'تسريع النشر 5x', 'اتساق الهوية 100%'],
    galleryIcons: ['ri-layout-2-line','ri-image-line','ri-gallery-line','ri-magic-line','ri-scissors-line','ri-crop-line']
  },
  {
    id: 'brochure-design',
    category: 'graphic',
    categoryLabel: 'الجرافيك',
    icon: 'ri-quill-pen-line',
    gradient: 'linear-gradient(135deg, #2d1b69 0%, #8e44ad 100%)',
    colors: ['#2d1b69', '#8e44ad', '#6c3483'],
    title: 'تصميم بروشور',
    shortDesc: 'تصميم بروشور تعريفي احترافي للشركات',
    fullDesc: 'صمّمنا بروشوراً تعريفياً فاخراً يجمع بين العمق السردي والتأثير البصري الساحر. كل صفحة مدروسة لتقود القارئ بسلاسة نحو فهم قيمة الشركة والثقة في خدماتها.\n\nعملنا على صياغة المحتوى المناسب لكل قسم بالتعاون مع فريق التسويق لدى العميل مع ضمان أعلى جودة طباعة ممكنة.\n\nالبروشور طُبع بمواد فاخرة ووُزّع في معرض دولي ليكون من أكثر المواد التسويقية تأثيراً في الفعالية.',
    client: 'شركة الإنشاءات والتطوير العمراني',
    year: '2024',
    services: ['تصميم البروشور', 'كتابة وتحرير المحتوى', 'إعداد ملفات الطباعة', 'تصميم الغلاف'],
    tags: ['InDesign', 'Photoshop', 'Illustrator', 'Print Production'],
    results: ['24 صفحة بجودة فائقة', 'طُبع 5000 نسخة', 'أفضل بروشور بالمعرض'],
    galleryIcons: ['ri-file-paper-2-line','ri-pages-line','ri-book-2-line','ri-typography','ri-image-add-line','ri-printer-line']
  },
  {
    id: 'banner-design',
    category: 'graphic',
    categoryLabel: 'الجرافيك',
    icon: 'ri-image-edit-line',
    gradient: 'linear-gradient(135deg, #1a1a1a 0%, #e07428 100%)',
    colors: ['#1a1a1a', '#e07428', '#d42b1e'],
    title: 'تصميم بنرات إعلانية',
    shortDesc: 'بنرات إعلانية بتصاميم حديثة وجذابة',
    fullDesc: 'أنتجنا حزمة بنرات إعلانية متكاملة تغطي جميع المقاسات القياسية الرقمية والمطبوعة للحملة الإعلانية الكبرى للعميل.\n\nصمّمنا البنرات بأسلوب بصري يأسر الانتباه خلال 3 ثوانٍ وينقل الرسالة بوضوح مع الحث على اتخاذ إجراء فوري.\n\nالحملة غطّت أكثر من 50 موقعاً رقمياً وإعلانات خارجية في 12 مدينة سعودية.',
    client: 'مجموعة أوبال العقارية',
    year: '2025',
    services: ['تصاميم بنرات رقمية', 'بنرات مطبوعة', 'إعلانات خارجية', 'بنرات سوشيال'],
    tags: ['Photoshop', 'Illustrator', 'After Effects', 'Google Display'],
    results: ['80+ مقاس مختلف', 'تغطية 12 مدينة', 'زيادة الوعي بالعلامة 65%'],
    galleryIcons: ['ri-image-edit-line','ri-artboard-line','ri-stack-line','ri-ruler-line','ri-external-link-line','ri-megaphone-line']
  },

  // ── Motion Graphic ────────────────────────────────────────────────────
  {
    id: 'motion-video',
    category: 'motion',
    categoryLabel: 'موشن جرافيك',
    icon: 'ri-movie-2-line',
    gradient: 'linear-gradient(135deg, #1a1a2e 0%, #e07428 100%)',
    colors: ['#1a1a2e', '#e07428', '#d42b1e'],
    title: 'فيديو موشن جرافيك',
    shortDesc: 'فيديو انفوجرافيك متحرك احترافي لعرض الخدمات',
    fullDesc: 'أنتجنا فيديو موشن جرافيك احترافياً مدته دقيقتان يشرح خدمات الشركة بأسلوب بصري ساحر يسهّل استيعاب المعلومات المعقدة ويرسّخها في الذاكرة.\n\nمررنا بمراحل التشريح الكامل من كتابة النص والستوري بورد إلى الرسوم التوضيحية والتحريك والموسيقى التصويرية.\n\nالفيديو حقق أكثر من 2 مليون مشاهدة عضوية وأصبح الفيديو التعريفي الرئيسي للشركة.',
    client: 'شركة حلول تقنية المستقبل',
    year: '2025',
    services: ['كتابة السيناريو', 'ستوري بورد', 'تصميم الرسوم', 'تحريك وتعديل'],
    tags: ['After Effects', 'Illustrator', 'Cinema 4D', 'Audition'],
    results: ['2M مشاهدة', 'مشاركة 50K+', 'عائد استثمار 1200%'],
    galleryIcons: ['ri-movie-2-line','ri-screenshot-line','ri-film-line','ri-palette-line','ri-music-line','ri-award-line']
  },
  {
    id: 'animated-ad',
    category: 'motion',
    categoryLabel: 'موشن جرافيك',
    icon: 'ri-play-circle-line',
    gradient: 'linear-gradient(135deg, #533483 0%, #e07428 100%)',
    colors: ['#533483', '#e07428', '#d42b1e'],
    title: 'إعلان متحرك',
    shortDesc: 'فيديو إعلاني متحرك للسوشيال ميديا',
    fullDesc: 'صنعنا إعلاناً متحركاً بمدة 30 ثانية مُحسّناً للأداء على منصات السوشيال ميديا بأسلوب بصري يمزج بين التشويق والوضوح الرسائلي.\n\nصُمّم الإعلان بثلاثة إصدارات مختلفة: واحد عمودي لتيك توك وإنستا ريلز، وأفقي ليوتيوب وفيسبوك، ومربع للبوست الاعتيادي.\n\nحقق الإعلان نسبة مشاهدة كاملة 78% مقارنة بالمعدل الصناعي البالغ 25%.',
    client: 'منتجات العناية بالبشرة Pure',
    year: '2024',
    services: ['إنتاج الإعلان', 'تعديل متعدد المنصات', 'Voiceover', 'مؤثرات صوتية'],
    tags: ['After Effects', 'Premiere Pro', 'Audition', 'DaVinci Resolve'],
    results: ['مشاهدة كاملة 78%', 'CTR 4.2%', 'مبيعات +180%'],
    galleryIcons: ['ri-play-circle-line','ri-video-add-line','ri-timer-line','ri-volume-up-line','ri-smartphone-line','ri-file-video-line']
  },
  {
    id: 'promo-video',
    category: 'motion',
    categoryLabel: 'موشن جرافيك',
    icon: 'ri-video-line',
    gradient: 'linear-gradient(135deg, #0c0c0c 0%, #d42b1e 100%)',
    colors: ['#0c0c0c', '#d42b1e', '#e07428'],
    title: 'فيديو تعريفي',
    shortDesc: 'فيديو تعريفي بالشركة بأسلوب الموشن جرافيك',
    fullDesc: 'أنتجنا فيديو تعريفياً بالشركة مدته 90 ثانية يحكي قصة نشأتها وقيمها ومنتجاتها بأسلوب موشن جرافيك راقٍ يترك انطباعاً لا يُنسى لدى المشاهد.\n\nاستخدمنا أسلوباً سردياً عاطفياً يربط المشاهد بالعلامة التجارية ويبني الثقة بشكل طبيعي قبل أي حديث عن المنتجات.\n\nاستُخدم الفيديو في العروض التقديمية وصفحة الموقع الرئيسية وحقق ارتفاعاً فورياً في نسبة التحويل بمقدار 95%.',
    client: 'شركة الابتكار الصناعي',
    year: '2025',
    services: ['سيناريو وقصة', 'تصوير وإخراج', 'موشن جرافيك', 'صوت وموسيقى'],
    tags: ['Cinema 4D', 'After Effects', 'Premiere Pro', 'Pro Tools'],
    results: ['رفع التحويل 95%', 'وقت بقاء الزوار +180%', 'مشاركات 10K+'],
    galleryIcons: ['ri-video-line','ri-clapperboard-line','ri-camera-line','ri-mic-line','ri-brush-3-line','ri-award-fill']
  },
  {
    id: 'animated-presentation',
    category: 'motion',
    categoryLabel: 'موشن جرافيك',
    icon: 'ri-film-line',
    gradient: 'linear-gradient(135deg, #141e30 0%, #243b55 100%)',
    colors: ['#141e30', '#243b55', '#3498db'],
    title: 'عرض تقديمي متحرك',
    shortDesc: 'عرض تقديمي احترافي بالرسوم المتحركة',
    fullDesc: 'صمّمنا عرضاً تقديمياً تفاعلياً يجمع بين الموشن جرافيك والانفوجرافيك عالي الجودة لتقديم خطة أعمال بأسلوب يُبهر المستثمرين ويُقنع صنّاع القرار.\n\nكل شريحة مُتحرّكة بعناية لتقود نظر المشاهد إلى نقطة التركيز الرئيسية مع توقيت مثالي يتناسب مع إيقاع المحاضر.\n\nالعرض استُخدم في جولة استثمارية ساهم في تأمين تمويل بـ 20 مليون ريال.',
    client: 'شركة ناشئة في التقنية المالية',
    year: '2024',
    services: ['تصميم الشرائح', 'موشن جرافيك', 'انفوجرافيك بيانات', 'صوتيات'],
    tags: ['PowerPoint Pro', 'After Effects', 'Figma', 'Lottie'],
    results: ['20M رسال تمويل', 'وقت العرض -30%', 'تأثير المستثمرين +200%'],
    galleryIcons: ['ri-presentation-line','ri-bar-chart-line','ri-pie-chart-line','ri-funds-box-line','ri-slideshow-3-line','ri-projector-2-line']
  },

  // ── Apps ──────────────────────────────────────────────────────────────
  {
    id: 'delivery-app',
    category: 'apps',
    categoryLabel: 'تطبيقات',
    icon: 'ri-smartphone-line',
    gradient: 'linear-gradient(135deg, #16213e 0%, #0f3460 100%)',
    colors: ['#16213e', '#0f3460', '#533483'],
    title: 'تطبيق توصيل طلبات',
    shortDesc: 'تصميم وتطوير تطبيق جوال متكامل لتوصيل الطلبات',
    fullDesc: 'طوّرنا تطبيقاً متكاملاً لتوصيل الطلبات يضم ثلاث واجهات مستقلة: للمستخدم والمطعم والمندوب، مع لوحة تحكم ويب لإدارة العمليات بالكامل.\n\nالتطبيق يضم تتبعاً للمندوب بالزمن الفعلي على الخريطة وأنظمة دفع متعددة وإشعارات فورية وتقييمات وتقارير متقدمة.\n\nالتطبيق خدم 50,000 مستخدم في الشهر الأول ووصل إلى 100 ألف طلب في الشهر الثالث.',
    client: 'منصة طعامك للتوصيل',
    year: '2025',
    services: ['تصميم UI/UX', 'تطوير iOS وAndroid', 'تطوير الخلفية', 'لوحة تحكم'],
    tags: ['Flutter', 'Firebase', 'Google Maps API', 'Node.js'],
    results: ['50K مستخدم أول شهر', '100K طلب ثالث شهر', 'تقييم 4.8/5 في المتجر'],
    galleryIcons: ['ri-smartphone-line','ri-map-pin-line','ri-motorbike-line','ri-shopping-bag-line','ri-notification-line','ri-star-line']
  },
  {
    id: 'business-app',
    category: 'apps',
    categoryLabel: 'تطبيقات',
    icon: 'ri-apps-2-line',
    gradient: 'linear-gradient(135deg, #0f3460 0%, #1a1a2e 100%)',
    colors: ['#0f3460', '#1a1a2e', '#533483'],
    title: 'تطبيق خدمات تجارية',
    shortDesc: 'تطبيق iOS و Android لإدارة الأعمال والخدمات',
    fullDesc: 'صمّمنا وطوّرنا تطبيقاً تجارياً شاملاً يُمكّن أصحاب الأعمال من إدارة فواتيرهم وعملائهم ومخزونهم ومواعيدهم من مكان واحد.\n\nالتطبيق يوفر تقارير مالية لحظية ولوحة بيانات ذكية ونظام CRM مبسّط وإمكانية التكامل مع أشهر أنظمة المحاسبة.\n\nحقق التطبيق تقييم 4.9 نجوم في App Store وتم اختياره تطبيق الأسبوع في متجر آبل السعودي.',
    client: 'منصة بيزنس برو',
    year: '2024',
    services: ['تصميم UI/UX', 'تطوير iOS', 'تطوير Android', 'تكاملات API'],
    tags: ['SwiftUI', 'Kotlin', 'GraphQL', 'Stripe', 'QuickBooks API'],
    results: ['4.9/5 App Store', 'تطبيق الأسبوع آبل', 'توفير وقت إدارة 70%'],
    galleryIcons: ['ri-apps-2-line','ri-file-chart-line','ri-contacts-book-line','ri-calendar-check-line','ri-money-cny-box-line','ri-dashboard-line']
  },
  {
    id: 'health-app',
    category: 'apps',
    categoryLabel: 'تطبيقات',
    icon: 'ri-health-book-line',
    gradient: 'linear-gradient(135deg, #1b2838 0%, #2a9d8f 100%)',
    colors: ['#1b2838', '#2a9d8f', '#1a5276'],
    title: 'تطبيق صحي',
    shortDesc: 'تطبيق حجز مواعيد طبية وإدارة ملفات المرضى',
    fullDesc: 'طوّرنا منصة صحية رقمية متكاملة تربط المرضى بالأطباء في ثوانٍ، مع إدارة الملفات الطبية والوصفات والنتائج بأمان تام ومتوافق مع معايير HIPAA.\n\nيتضمن التطبيق استشارات طبية عبر الفيديو وتذكيرات الأدوية وتتبع المؤشرات الحيوية ونظام ذكاء اصطناعي للتوصية بالأطباء المناسبين.\n\nحقق التطبيق مليون مستخدم في العام الأول ووُصف بـ"ثورة في الرعاية الصحية الرقمية" في أحد التقارير الإعلامية.',
    client: 'شبكة عيادات الشفاء الرقمي',
    year: '2025',
    services: ['تصميم UI/UX محوري للمريض', 'تطوير متعدد المنصات', 'نظام التشفير الطبي', 'AI توصية'],
    tags: ['React Native', 'Python/Django', 'PostgreSQL', 'WebRTC'],
    results: ['1M مستخدم أول عام', 'تقليل انتظار المواعيد 80%', 'رضا المرضى 96%'],
    galleryIcons: ['ri-health-book-line','ri-hospital-line','ri-psychiatric-line','ri-heart-pulse-line','ri-stethoscope-line','ri-user-heart-line']
  },
  {
    id: 'restaurant-app',
    category: 'apps',
    categoryLabel: 'تطبيقات',
    icon: 'ri-restaurant-line',
    gradient: 'linear-gradient(135deg, #2c3e50 0%, #4ca1af 100%)',
    colors: ['#2c3e50', '#4ca1af', '#1a5276'],
    title: 'تطبيق مطاعم',
    shortDesc: 'تطبيق إدارة مطاعم بواجهة عصرية وسهلة الاستخدام',
    fullDesc: 'صمّمنا تطبيقاً لإدارة المطاعم يغطي تجربة العميل من عرض المنيو التفاعلي مروراً بالطلب والدفع وصولاً إلى تقييم التجربة، مع نظام إدارة داخلي للمطبخ والكاشير.\n\nالتطبيق يدعم الطلب من داخل المطعم عبر QR Code والطلب المسبق قبل الوصول والطلب للتوصيل والاستلام.\n\nوفّر التطبيق للمطعم خفضاً في تكاليف التشغيل بنسبة 35% وزيادة في متوسط قيمة الطلب بنسبة 28%.',
    client: 'سلسلة مطاعم البيت الكبير',
    year: '2024',
    services: ['تصميم تجربة المطعم', 'تطوير تطبيق العميل', 'نظام إدارة المطبخ', 'نظام الكاشير'],
    tags: ['React Native', 'NestJS', 'Redis', 'Square POS'],
    results: ['توفير تكاليف 35%', 'رفع قيمة الطلب 28%', 'تقييم 4.7/5'],
    galleryIcons: ['ri-restaurant-line','ri-fork-line','ri-qr-code-line','ri-receipt-line','ri-tablet-line','ri-team-line']
  }

];
